version: '3'

services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 2

  memcached:
    image: memcached
    ports:
      - "11211:11211"
    entrypoint:
      - memcached
      - -m 64

  web:
    build: sych_app
    command: python3 start.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - postgres:
        condition: service_healthy
    depends_on:
       - memcached
    links:
      - postgres:postgres
      - memcached:memcached

  nginx:
    restart: always
    build: nginx
    ports:
      - "80:80"
    links:
      - web:web
    depends_on:
      - web
